/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pwr_karmil_DiscreteFunc */

#ifndef _Included_pwr_karmil_DiscreteFunc
#define _Included_pwr_karmil_DiscreteFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pwr_karmil_DiscreteFunc
 * Method:    nativeFunc
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_pwr_karmil_DiscreteFunc_nativeFunc
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
